2024-11-02 17:39:55,007 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:57]
2024-11-02 17:39:56,210 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:59]
2024-11-02 17:40:11,045 ERROR: An error occurred: 405 Method Not Allowed: The method is not allowed for the requested URL. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:16]
Traceback (most recent call last):
  File "c:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "c:\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "c:\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "c:\Python310\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2024-11-02 17:40:16,981 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:45]
2024-11-02 17:40:18,820 ERROR: Error in /stop-model endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:50]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 46, in stop_model
    StopModelUseCase().execute()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\stop_model_use_case.py", line 8, in execute
    return self.label_repository.stop_model()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\label_repository.py", line 14, in stop_model
    return self.rekognition_service.stop_model()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\aws_rekognition_service.py", line 28, in stop_model
    response = self.client.stop_project_version(
  File "c:\Python310\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\Python310\lib\site-packages\botocore\client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUseException) when calling the StopProjectVersion operation: ProjectVersion arn:aws:rekognition:us-east-2:654654415025:project/Parking_lot/version/Parking_lot.2024-09-04T18.47.11/1725490031705 is STOPPED; cannot be stopped
2024-11-02 17:45:24,674 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:45]
2024-11-02 17:45:25,891 ERROR: Error in /stop-model endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:50]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 46, in stop_model
    StopModelUseCase().execute()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\stop_model_use_case.py", line 11, in execute
    raise ModelAlreadyStoppedException("Model is already stopped")
app.core.exceptions.ModelAlreadyStoppedException: Model is already stopped
2024-11-02 17:46:06,005 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:45]
2024-11-02 17:46:07,031 ERROR: Error in /stop-model endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:50]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 46, in stop_model
    StopModelUseCase().execute()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\stop_model_use_case.py", line 11, in execute
    raise ModelAlreadyStoppedException("Model is already stopped")
app.core.exceptions.ModelAlreadyStoppedException: Model is already stopped
2024-11-02 17:47:00,764 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:45]
2024-11-02 17:47:01,970 ERROR: Error in /stop-model endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:50]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 46, in stop_model
    StopModelUseCase().execute()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\stop_model_use_case.py", line 11, in execute
    raise ModelAlreadyStoppedException("Model is already stopped")
app.core.exceptions.ModelAlreadyStoppedException: Model is already stopped
2024-11-02 17:47:35,280 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:45]
2024-11-02 17:48:02,840 ERROR: Error in /stop-model endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:50]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 46, in stop_model
    StopModelUseCase().execute()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\stop_model_use_case.py", line 11, in execute
    raise ModelAlreadyStoppedException("Model is already stopped")
app.core.exceptions.ModelAlreadyStoppedException: Model is already stopped
2024-11-02 17:50:02,944 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 17:50:07,771 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-02 18:05:30,210 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 18:05:31,340 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-02 18:28:35,910 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-02 18:28:38,210 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-02 18:28:38,213 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-02 18:28:38,989 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-02 18:28:39,001 WARNING: No image found in the request. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:15]
2024-11-02 18:28:39,004 INFO: Received image for label detection [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:19]
2024-11-02 18:28:39,773 ERROR: Error in /detect-labels endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:27]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 22, in detect_labels
    labels = DetectLabelsUseCase().execute(image)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\detect_label_use_case.py", line 8, in execute
    labels = self.label_repository.detect_labels(image_bytes)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\label_repository.py", line 8, in detect_labels
    return self.rekognition_service.detect_labels(image_bytes)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\aws_rekognition_service.py", line 14, in detect_labels
    response = self.client.detect_labels(
  File "C:\Python310\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Python310\lib\site-packages\botocore\client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the DetectLabels operation: User: arn:aws:iam::654654415025:user/Jose.F is not authorized to perform: rekognition:DetectLabels because no identity-based policy allows the rekognition:DetectLabels action
2024-11-02 18:28:39,783 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-02 18:28:40,818 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-02 18:28:40,820 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-02 18:28:41,797 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-02 18:28:41,802 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 18:28:42,573 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-02 18:28:42,576 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 18:28:43,459 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-02 18:34:25,136 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 18:34:26,437 INFO: Model stopped successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:51]
2024-11-02 18:34:57,367 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-02 18:34:58,322 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-02 18:34:58,325 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-02 18:34:59,852 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-02 18:34:59,854 WARNING: No image found in the request. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:15]
2024-11-02 18:34:59,856 INFO: Received image for label detection [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:19]
2024-11-02 18:35:00,786 ERROR: Error in /detect-labels endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:27]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 22, in detect_labels
    labels = DetectLabelsUseCase().execute(image)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\detect_label_use_case.py", line 8, in execute
    labels = self.label_repository.detect_labels(image_bytes)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\label_repository.py", line 8, in detect_labels
    return self.rekognition_service.detect_labels(image_bytes)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\aws_rekognition_service.py", line 14, in detect_labels
    response = self.client.detect_labels(
  File "C:\Python310\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Python310\lib\site-packages\botocore\client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidImageFormatException: An error occurred (InvalidImageFormatException) when calling the DetectLabels operation: Request has invalid image format
2024-11-02 18:35:00,793 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-02 18:35:01,788 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-02 18:35:01,790 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-02 18:35:02,805 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-02 18:35:02,807 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 18:35:03,613 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-02 18:35:03,616 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 18:35:04,386 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-02 18:37:35,163 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-02 18:37:36,317 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-02 18:37:36,320 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-02 18:37:38,953 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-02 18:37:38,956 WARNING: No image found in the request. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:15]
2024-11-02 18:37:38,959 INFO: Received image for label detection [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:19]
2024-11-02 18:37:39,861 ERROR: Error in /detect-labels endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:27]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 22, in detect_labels
    labels = DetectLabelsUseCase().execute(image)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\detect_label_use_case.py", line 8, in execute
    labels = self.label_repository.detect_labels(image_bytes)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\label_repository.py", line 8, in detect_labels
    return self.rekognition_service.detect_labels(image_bytes)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\aws_rekognition_service.py", line 14, in detect_labels
    response = self.client.detect_labels(
  File "C:\Python310\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Python310\lib\site-packages\botocore\client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidImageFormatException: An error occurred (InvalidImageFormatException) when calling the DetectLabels operation: Request has invalid image format
2024-11-02 18:37:39,868 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-02 18:37:40,995 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-02 18:37:40,997 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-02 18:37:42,039 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-02 18:37:42,042 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 18:37:42,816 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-02 18:37:42,818 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 18:37:43,575 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-02 18:38:22,988 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-02 18:38:23,785 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-02 18:38:53,788 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-02 18:38:54,704 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-02 18:40:06,613 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-02 18:40:08,344 INFO: Model status: Running [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-02 18:40:14,467 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-02 18:40:15,472 INFO: Model stopped successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:51]
2024-11-06 21:34:10,689 ERROR: An error occurred: 405 Method Not Allowed: The method is not allowed for the requested URL. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:26]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2024-11-06 21:34:15,147 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-06 21:34:16,606 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-06 21:34:28,924 ERROR: An error occurred: 405 Method Not Allowed: The method is not allowed for the requested URL. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:26]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2024-11-06 21:34:33,851 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-06 21:34:34,889 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-07 18:28:57,614 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-07 18:28:59,865 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-07 18:30:01,891 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-07 18:30:02,765 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-07 18:30:36,539 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-07 18:30:37,328 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:54]
2024-11-07 18:38:36,685 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:38:37,526 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:39:05,204 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:39:06,021 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:39:17,037 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:39:18,072 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:43:18,060 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:43:19,171 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:53:33,921 ERROR: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:26]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-07 18:54:21,366 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:54:22,192 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:54:25,156 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:54:25,962 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:55:10,483 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:55:11,497 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:55:12,487 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:55:13,294 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:56:01,381 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:56:02,230 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:56:06,117 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:56:06,906 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:57:21,371 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:57:22,434 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:58:24,131 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:58:25,202 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:59:30,062 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:59:30,919 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:59:38,616 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:59:40,137 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:59:40,212 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:59:41,003 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 18:59:42,605 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 18:59:43,388 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:00:07,929 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:00:08,719 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:01:45,296 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:01:46,126 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:01:58,926 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:02:02,964 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:06:47,809 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:06:48,696 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:06:52,976 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:06:53,776 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:07:21,761 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:07:22,543 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:07:38,364 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:07:39,157 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:07:52,389 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:07:53,244 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:07:55,721 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:07:56,538 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:08:18,960 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:08:19,755 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:08:24,210 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:08:24,998 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:09:07,503 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:09:08,343 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:09:21,166 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:09:21,945 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:09:35,851 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:09:36,630 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:10:23,842 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:10:24,676 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:10:33,505 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:10:34,292 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:12:34,163 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:12:35,055 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:12:53,679 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:12:54,473 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:13:05,190 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:13:05,981 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:13:54,126 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:13:54,968 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:14:22,589 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:14:23,362 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:14:25,835 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:14:26,621 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:14:36,651 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:14:37,452 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:15:04,350 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:15:05,174 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:29:25,549 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:29:26,358 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:35:30,902 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:35:31,999 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:35:47,014 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:35:47,797 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:36:42,862 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:36:43,682 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:36:57,681 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:36:58,485 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:38:11,475 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:38:12,289 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:38:54,454 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:38:55,229 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:39:03,216 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:39:04,058 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:39:09,077 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:39:09,879 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:39:18,669 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-07 19:39:19,698 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-07 19:39:48,936 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:39:49,741 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:39:51,726 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:39:52,577 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:39:56,069 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-07 19:39:57,108 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-07 19:41:06,462 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:41:07,549 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:41:10,756 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-07 19:41:11,771 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-07 19:42:36,306 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:42:37,150 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:42:59,793 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:43:00,573 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:43:17,966 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:43:18,746 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:43:34,883 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:43:35,709 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:43:49,877 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:43:50,858 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:45:30,108 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:45:30,959 INFO: Model status: Running [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:45:40,735 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:49]
2024-11-07 19:45:41,855 INFO: Model stopped successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:51]
2024-11-07 19:45:58,440 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:45:59,230 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:46:32,490 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:46:33,312 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:47:09,522 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:47:10,326 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:47:17,581 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:47:18,373 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:47:42,564 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:47:43,406 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:47:44,960 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:47:45,746 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 19:48:09,441 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:34]
2024-11-07 19:48:10,507 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:36]
2024-11-07 19:58:51,878 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:64]
2024-11-07 19:58:52,710 INFO: Model status: Running [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:66]
2024-11-07 21:06:41,897 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:111]
2024-11-07 21:06:42,772 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:113]
2024-11-07 21:08:30,824 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:111]
2024-11-07 21:08:31,669 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:113]
2024-11-07 21:09:08,167 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:111]
2024-11-07 21:09:08,967 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py:113]
2024-11-08 21:56:17,749 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:34]
2024-11-08 21:56:19,490 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:36]
2024-11-08 23:05:54,868 ERROR: An error occurred: 405 Method Not Allowed: The method is not allowed for the requested URL. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2024-11-08 23:05:58,906 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:23]
2024-11-08 23:05:59,852 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:28]
2024-11-09 02:08:11,703 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:34]
2024-11-09 02:08:12,822 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:36]
2024-11-11 01:17:09,363 ERROR: An error occurred: module 'datetime' has no attribute 'now' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 32, in insert_parking_spot
    return ParkingLotController.insert_parking_spot(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\parking_lot_controller.py", line 29, in insert_parking_spot
    created_at=datetime.now()
AttributeError: module 'datetime' has no attribute 'now'
2024-11-11 01:23:57,169 ERROR: An error occurred: InsertParkingSpot.execute() missing 1 required positional argument: 'parking_spot' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 32, in insert_parking_spot
    return ParkingLotController.insert_parking_spot(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\parking_lot_controller.py", line 23, in insert_parking_spot
    InsertParkingSpot.execute(
TypeError: InsertParkingSpot.execute() missing 1 required positional argument: 'parking_spot'
2024-11-11 01:24:29,295 ERROR: An error occurred: InsertParkingSpot.execute() missing 1 required positional argument: 'self' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 32, in insert_parking_spot
    return ParkingLotController.insert_parking_spot(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\parking_lot_controller.py", line 23, in insert_parking_spot
    InsertParkingSpot.execute(
TypeError: InsertParkingSpot.execute() missing 1 required positional argument: 'self'
2024-11-11 01:59:01,849 ERROR: An error occurred: 'name' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 32, in insert_parking_spot
    return ParkingLotController.insert_parking_spot(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\parking_lot_controller.py", line 25, in insert_parking_spot
    name=data['name'],
KeyError: 'name'
2024-11-15 22:43:05,409 ERROR: An error occurred: Can't instantiate abstract class CameraService with abstract method detect_labels [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 37, in insert_parking_spot
    return ParkingSpotController.insert_parking_spot(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\parking_spot_controller.py", line 21, in insert_parking_spot
    return InsertCameraUseCase().execute(
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\camera_use_cases\insert_camera_use_case.py", line 7, in __init__
    self.camera_repository = CameraRepository()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\camera_repository\camera_repository.py", line 6, in __init__
    self.camera_service = camera_service or CameraService()
TypeError: Can't instantiate abstract class CameraService with abstract method detect_labels
2024-11-15 22:46:51,027 ERROR: An error occurred: Can't instantiate abstract class CameraService with abstract method detect_labels [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 37, in insert_parking_spot
    return ParkingSpotController.insert_parking_spot(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\parking_spot_controller.py", line 21, in insert_parking_spot
    return InsertCameraUseCase().execute(
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\camera_use_cases\insert_camera_use_case.py", line 7, in __init__
    self.camera_repository = CameraRepository()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\camera_repository\camera_repository.py", line 6, in __init__
    self.camera_service = camera_service or CameraService()
TypeError: Can't instantiate abstract class CameraService with abstract method detect_labels
2024-11-15 22:48:42,254 ERROR: An error occurred: Can't instantiate abstract class ParkingSpotService with abstract method detect_labels [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 37, in insert_parking_spot
    return ParkingSpotController.insert_parking_spot(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\parking_spot_controller.py", line 22, in insert_parking_spot
    return InsertParkingSpotUseCase().execute(
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\parking_spot_use_cases\insert_parking_spot_use_case.py", line 6, in __init__
    self.parking_spot_repository = ParkingSpotRepository()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\parking_spot_repository\parking_spot_repository.py", line 6, in __init__
    self.parking_spot_service = ParkingSpotService()
TypeError: Can't instantiate abstract class ParkingSpotService with abstract method detect_labels
2024-11-15 22:51:49,168 ERROR: An error occurred: Can't instantiate abstract class ParkingSpotService with abstract method delete_parking_spor [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 37, in insert_parking_spot
    return ParkingSpotController.insert_parking_spot(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\parking_spot_controller.py", line 22, in insert_parking_spot
    return InsertParkingSpotUseCase().execute(
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\parking_spot_use_cases\insert_parking_spot_use_case.py", line 6, in __init__
    self.parking_spot_repository = ParkingSpotRepository()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\parking_spot_repository\parking_spot_repository.py", line 6, in __init__
    self.parking_spot_service = ParkingSpotService()
TypeError: Can't instantiate abstract class ParkingSpotService with abstract method delete_parking_spor
2024-11-15 22:52:15,677 ERROR: An error occurred: 'parking_spot_id' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 37, in insert_parking_spot
    return ParkingSpotController.insert_parking_spot(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\parking_spot_controller.py", line 24, in insert_parking_spot
    name= data['parking_spot_id'],
KeyError: 'parking_spot_id'
2024-11-15 23:54:06,414 ERROR: An error occurred: 405 Method Not Allowed: The method is not allowed for the requested URL. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2024-11-16 00:16:28,360 ERROR: An error occurred: Can't instantiate abstract class CameraService with abstract method detect_labels [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 54, in get_cameras
    return CameraController.get_cameras()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\camera_controller.py", line 14, in get_cameras
    return GetCamerasUseCase().execute()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\camera_use_cases\get_cameras_use_case.py", line 5, in __init__
    self.camera_repository = CameraRepository()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\camera_repository\camera_repository.py", line 6, in __init__
    self.camera_service = camera_service or CameraService()
TypeError: Can't instantiate abstract class CameraService with abstract method detect_labels
2024-11-16 01:35:44,483 ERROR: An error occurred: 405 Method Not Allowed: The method is not allowed for the requested URL. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2024-11-16 01:43:57,562 ERROR: An error occurred: 405 Method Not Allowed: The method is not allowed for the requested URL. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2024-11-16 01:44:06,465 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:81]
2024-11-16 01:44:06,768 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:83]
2024-11-16 01:44:11,430 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:70]
2024-11-16 01:44:11,433 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:75]
2024-11-16 14:18:25,323 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:59]
2024-11-16 14:18:25,628 ERROR: An error occurred: 'ModelService' object has no attribute 'model_arn' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 16, in start_model
    return ModelController.start_model()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py", line 60, in start_model
    StartModelUseCase().execute()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\model_use_cases\start_model_use_case.py", line 14, in execute
    response = self.model_repository.start_model()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\model_repository\model_repository.py", line 11, in start_model
    return self.model_service.start_model()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py", line 22, in start_model
    ProjectVersionArn=self.model_arn,
AttributeError: 'ModelService' object has no attribute 'model_arn'
2024-11-16 14:19:37,996 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:59]
2024-11-16 14:19:38,144 ERROR: An error occurred: 'ModelService' object has no attribute 'min_inference_units' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 16, in start_model
    return ModelController.start_model()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py", line 60, in start_model
    StartModelUseCase().execute()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\model_use_cases\start_model_use_case.py", line 14, in execute
    response = self.model_repository.start_model()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\model_repository\model_repository.py", line 11, in start_model
    return self.model_service.start_model()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py", line 24, in start_model
    MinInferenceUnits=self.min_inference_units
AttributeError: 'ModelService' object has no attribute 'min_inference_units'
2024-11-16 14:37:38,275 INFO: Starting the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:59]
2024-11-16 14:37:40,393 INFO: Model started successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:61]
2024-11-16 15:09:04,477 ERROR: An error occurred: Can't instantiate abstract class AWSService with abstract methods detect_labels, is_model_running, start_model, stop_model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 35, in insert_image
    UploadImageToS3UseCase().execute(
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\image_use_cases\upload_image_to_s3.py", line 6, in __init__
    self.aws_repository = AwsRepository()
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\aws_repository\aws_repository.py", line 6, in __init__
    self.aws_service = aws_service or AWSService()
TypeError: Can't instantiate abstract class AWSService with abstract methods detect_labels, is_model_running, start_model, stop_model
2024-11-16 15:12:15,993 ERROR: An error occurred: ImageHelper.draw_labels_to_image() got an unexpected keyword argument 'draw_label' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 46, in insert_image
    image_labeled = ImageHelper().draw_labels_to_image(
TypeError: ImageHelper.draw_labels_to_image() got an unexpected keyword argument 'draw_label'
2024-11-16 15:17:09,230 ERROR: An error occurred: 'tuple' object has no attribute 'image' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 60, in insert_image
    S3ImageData(image_data=image_labeled.image, file_name=labeled_file_name, bucket_name=bucket_name)
AttributeError: 'tuple' object has no attribute 'image'
2024-11-16 15:18:33,203 ERROR: An error occurred: 'tuple' object has no attribute 'image' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 61, in insert_image
    S3ImageData(image_data=image_labeled.image, file_name=labeled_file_name, bucket_name=bucket_name)
AttributeError: 'tuple' object has no attribute 'image'
2024-11-16 15:20:27,300 ERROR: An error occurred: Failed to draw label in image: 'bytes' object has no attribute 'load' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\PIL\ImageDraw.py", line 865, in Draw
    return im.getdraw(mode)
AttributeError: 'bytes' object has no attribute 'getdraw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\helpers\image_helper.py", line 30, in draw_labels_to_image
    draw = ImageDraw.Draw(draw_labels_data.image)
  File "C:\Python310\lib\site-packages\PIL\ImageDraw.py", line 867, in Draw
    return ImageDraw(im, mode)
  File "C:\Python310\lib\site-packages\PIL\ImageDraw.py", line 64, in __init__
    im.load()
AttributeError: 'bytes' object has no attribute 'load'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 49, in insert_image
    image_labeled = ImageHelper().draw_labels_to_image(
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\helpers\image_helper.py", line 45, in draw_labels_to_image
    raise RuntimeError(f"Failed to draw label in image: {e}")
RuntimeError: Failed to draw label in image: 'bytes' object has no attribute 'load'
2024-11-16 15:22:30,184 ERROR: An error occurred: Parameter validation failed:
Invalid type for parameter Image.Bytes, value: <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1280x720 at 0x228DFE0C910>, type: <class 'PIL.JpegImagePlugin.JpegImageFile'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 45, in insert_image
    labels = DetectLabelsUseCase().execute(image_data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\model_use_cases\detect_label_use_case.py", line 8, in execute
    labels = self.model_repository.detect_labels(image_bytes)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\model_repository\model_repository.py", line 8, in detect_labels
    return self.model_service.detect_labels(image_bytes)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py", line 13, in detect_labels
    response = self.aws_client.detect_custom_labels(
  File "C:\Python310\lib\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Python310\lib\site-packages\botocore\client.py", line 923, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "C:\Python310\lib\site-packages\botocore\client.py", line 991, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "C:\Python310\lib\site-packages\botocore\validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Image.Bytes, value: <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1280x720 at 0x228DFE0C910>, type: <class 'PIL.JpegImagePlugin.JpegImageFile'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object
2024-11-16 15:26:00,406 ERROR: An error occurred: ImageHelper.decode_base64_image() takes 1 positional argument but 2 were given [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 25, in insert_image
    image_data = ImageHelper().decode_base64_image(data['image'])
TypeError: ImageHelper.decode_base64_image() takes 1 positional argument but 2 were given
2024-11-16 15:26:23,713 ERROR: An error occurred: Failed to draw label in image: 'bytes' object has no attribute 'load' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\PIL\ImageDraw.py", line 865, in Draw
    return im.getdraw(mode)
AttributeError: 'bytes' object has no attribute 'getdraw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\helpers\image_helper.py", line 28, in draw_labels_to_image
    draw = ImageDraw.Draw(draw_labels_data.image)
  File "C:\Python310\lib\site-packages\PIL\ImageDraw.py", line 867, in Draw
    return ImageDraw(im, mode)
  File "C:\Python310\lib\site-packages\PIL\ImageDraw.py", line 64, in __init__
    im.load()
AttributeError: 'bytes' object has no attribute 'load'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 50, in insert_image
    image_labeled = ImageHelper().draw_labels_to_image(
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\helpers\image_helper.py", line 43, in draw_labels_to_image
    raise RuntimeError(f"Failed to draw label in image: {e}")
RuntimeError: Failed to draw label in image: 'bytes' object has no attribute 'load'
2024-11-16 15:29:50,410 ERROR: An error occurred: S3ImageData.__init__() missing 1 required positional argument: 'max_results' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 65, in insert_image
    S3ImageData(image_data=image_labeled.image, file_name=labeled_file_name, bucket_name=bucket_name)
TypeError: S3ImageData.__init__() missing 1 required positional argument: 'max_results'
2024-11-16 15:31:55,235 ERROR: An error occurred: ImageData.__init__() got an unexpected keyword argument 'free_count' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 78, in insert_image
    image_data= ImageData(
TypeError: ImageData.__init__() got an unexpected keyword argument 'free_count'
2024-11-16 15:33:20,269 ERROR: An error occurred: InsertImageUseCase.execute() got an unexpected keyword argument 'image_data' [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 88, in insert_image
    return ImageController.insert_image(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\image_controller.py", line 77, in insert_image
    InsertImageUseCase().execute(
TypeError: InsertImageUseCase.execute() got an unexpected keyword argument 'image_data'
2024-11-16 15:56:42,444 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:70]
2024-11-16 15:56:42,447 WARNING: Model is already stopped. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:75]
2024-11-16 15:57:06,328 INFO: Checking model status [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:81]
2024-11-16 15:57:06,332 INFO: Model status: Stopped [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\model_controller.py:83]
2024-11-16 16:01:59,152 ERROR: Error in /model-status endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:49]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py", line 42, in is_model_running
    ProjectArn=self.project_arn,
AttributeError: 'ModelService' object has no attribute 'project_arn'
2024-11-16 16:02:57,600 INFO: Model status: RUNNING [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:48]
2024-11-16 16:03:15,273 INFO: Model status: RUNNING [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:48]
2024-11-16 16:06:34,901 INFO: Model status: RUNNING [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:58]
2024-11-16 16:06:34,901 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:37]
2024-11-16 16:06:35,125 INFO: Model stopped successfully [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:41]
2024-11-16 16:06:42,065 INFO: Model status: STOPPED [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:58]
2024-11-16 16:06:42,066 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:37]
2024-11-16 16:06:42,275 WARNING: Error in /model/stop endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:47]
2024-11-16 16:07:17,512 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:37]
2024-11-16 16:07:17,513 WARNING: Error in /model/stop endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:51]
2024-11-16 16:07:50,474 INFO: Stopping the model [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:37]
2024-11-16 16:07:51,403 WARNING: Error in /model/stop endpoint [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:47]
2024-11-16 16:11:38,090 INFO: Model status: STOPPED [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\model_service.py:61]
2025-01-04 12:56:35,883 ERROR: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\user\Documents\tesis\amazon-rekognition-py\app\main.py:27]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-01-04 12:59:08,913 ERROR: An error occurred: 405 Method Not Allowed: The method is not allowed for the requested URL. [in C:\Users\user\Documents\tesis\amazon-rekognition-py\app\main.py:27]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\werkzeug\routing\map.py", line 624, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2025-01-04 12:59:18,239 ERROR: An error occurred: You must specify a region. [in C:\Users\user\Documents\tesis\amazon-rekognition-py\app\main.py:27]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\api\routes.py", line 20, in stop_model
    return ModelController.stop_model()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\api\controllers\model_controller.py", line 62, in stop_model
    return StopModelUseCase().execute()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\core\use_cases\model_use_cases\stop_model_use_case.py", line 6, in __init__
    self.model_repository = ModelRepository()
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\data\repositories\model_repository\model_repository.py", line 5, in __init__
    self.model_service = model_service or ModelService()
                                          ^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\data\services\model_service.py", line 10, in __init__
    self.aws_client = boto3.client('rekognition', region_name=Config.AWS_REGION)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\boto3\__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\boto3\session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\session.py", line 976, in create_client
    client = client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\client.py", line 155, in create_client
    client_args = self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\client.py", line 485, in _get_client_args
    return args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\args.py", line 92, in get_client_args
    final_args = self.compute_client_args(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\args.py", line 205, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\args.py", line 313, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\args.py", line 418, in _resolve_endpoint
    return endpoint_bridge.resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\client.py", line 590, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\regions.py", line 229, in construct_endpoint
    result = self._endpoint_for_partition(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
2025-01-08 16:40:24,466 INFO: Stopping the model [in C:\Users\user\Documents\tesis\amazon-rekognition-py\app\data\services\model_service.py:43]
2025-01-08 16:40:28,376 WARNING: Error in /model/stop endpoint [in C:\Users\user\Documents\tesis\amazon-rekognition-py\app\data\services\model_service.py:53]
2025-01-08 16:49:48,215 ERROR: An error occurred: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'. [in C:\Users\user\Documents\tesis\amazon-rekognition-py\app\main.py:27]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\api\routes.py", line 16, in login_user
    data = request.get_json()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2025-01-08 16:51:16,665 ERROR: An error occurred: 'dict' object has no attribute 'user' [in C:\Users\user\Documents\tesis\amazon-rekognition-py\app\main.py:27]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\api\routes.py", line 17, in login_user
    return "Tu usuario es " + data.user
                              ^^^^^^^^^
AttributeError: 'dict' object has no attribute 'user'
2025-01-10 13:35:35,209 ERROR: An error occurred: AuthRepository.register_user() got an unexpected keyword argument 'login_data' [in C:\Users\user\Documents\tesis\amazon-rekognition-py\app\main.py:27]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\api\routes.py", line 24, in register_user
    return AuthController.register_user(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\api\controllers\auth_controller.py", line 23, in register_user
    return RegisterUserUseCase().execute(user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Documents\tesis\amazon-rekognition-py\app\core\use_cases\auth_use_cases\register_user_use_case.py", line 9, in execute
    response = self.auth_repository.register_user(login_data=register_user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AuthRepository.register_user() got an unexpected keyword argument 'login_data'
2025-01-16 01:13:10,918 ERROR: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-01-16 01:14:25,774 ERROR: An error occurred: name 'e' is not defined [in C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\main.py:27]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\auth_service.py", line 22, in login
    access_token = jwt.encode({
AttributeError: module 'jwt' has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\routes.py", line 20, in login_user
    return AuthController.login(data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\api\controllers\auth_controller.py", line 15, in login
    return LoginUseCase().execute(login_data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\core\use_cases\auth_use_cases\login_use_case.py", line 9, in execute
    response = self.auth_repository.login(login_data=login_data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\repositories\auth_repository\auth_repository.py", line 9, in login
    return self.auth_service.login(login_data=login_data)
  File "C:\Users\User\Documents\Tesis\parking_lot_api\new api\app\data\services\auth_service.py", line 32, in login
    except (e):
NameError: name 'e' is not defined
